### ISSUE TITLE
Injection results for ds != 1 cannot be saved

### ISSUE THREAD

**Issue by HarrisonS-Phys** [maxisi/ringdown#41]
When loading a config file using ringdown.Fit.from_config(), and then running the fit, if ds != 1 then the result object is not properly saved and the run crashes. This happens after the sampling itself has completed.

**Comment by maxisi** [comment]
Please provide the full traceback (and ideally minimum working code to reproduce the error)

**Comment by maxisi** [comment]
I cannot reproduce this so I'm closing this issue, please reopen as needed
