### ISSUE TITLE
Data conditioning issues

### ISSUE THREAD

**Issue by Steve-Hawk** [maxisi/ringdown#57]
- will this sharp cutoff in the frequency domain cause unwanted artifacts (like Gibbs phenomenon) when transforming the signal back into the time domain? (though the digital filter seems to be better than smoother transition filters from your paper [2410.02704](https://arxiv.org/abs/2410.02704))
https://github.com/maxisi/ringdown/blob/47d14a8ce84698f349b0faf43757564be207b175/ringdown/data.py#L604

- If the input parameter `fmax` from the `condition` function is set equal to the Nyquist frequency, it will satisfy the condition in
https://github.com/maxisi/ringdown/blob/c09224f4473762b2a8509f26c253f4fb80889e16/ringdown/data.py#L587
where a low-pass filter is applied in the following block:
https://github.com/maxisi/ringdown/blob/c09224f4473762b2a8509f26c253f4fb80889e16/ringdown/data.py#L592
In this case, even if we specify a digital filter, it won't make any difference, because frequencies below the Nyquist frequency would have already be affected.

**Comment by maxisi** [comment]
Hi @Steve-Hawk ,

1. The sharp cutoff in the FD may have a slight impact on the TD data, which might be undesirable for plotting but we find that it does not affect the likelihood and is, in fact, preferable to other filters (cf., [arXiv:2410.02704](https://arxiv.org/abs/2410.02704); you can also find a short discussion of this in Numerical Recipes. If if you notice any issues, do let us know.

2. This behavior is intended in case one wants to apply the Butterworth filter without downsampling; if you do not want to apply this filter you should not pass `f_max`. To make this clear, we can add a warning to alert the user of this when `f_max` is the Nyquist frequency.

I hope this answers your questions! Let us know if you have further comments.
